#using try and exception

# try:
#     age=int(input('What\'s your age?'))

# except:
#     if ValueError: #In this case avoid errors and give opportunities to try again without crash the code
#         print("Try again with a valid numeric number")   
#         age=int(input('What\'s your age?'))

# if age > 18:
#     print(f"you are {age} years old. You can drive")    

# import random

# def sum_num(numa, numb):
#     return numa + numb

# # Usando debugin
# def list_a(list_mu):
#     list_b = []
#     new_item=0
#     for i in list_mu:
#         new_item = i * 2
#         new_item += random.randint(1, 3)
#         new_item = sum_num(new_item, i)
#         list_b.append(new_item)

#     print(list_b)

# # chamada da função fora da definição




# resultado = list_a([1,2,3,4,5,6,7,8,9,10])



